### ISSUE TITLE
Uncaught Error: Failed to spawn '/home/liam/.cache/astral/121.0.6130.0/chrome-linux64/chrome': Exec format error (os error 8)

### ISSUE THREAD

**Issue by DNAScanner** [lino-levan/astral#51]
Hey. I just tried using astral for the first time, but immediately after launching the browser, the script threw an error and crashed.

Code:
```ts
import { launch } from "https://deno.land/x/astral/mod.ts";
const browser = await launch();
```

Error:
```ts
Uncaught Error: Failed to spawn '/home/liam/.cache/astral/121.0.6130.0/chrome-linux64/chrome': Exec format error (os error 8)
    at spawnChildInner (ext:runtime/40_process.js:185:17)
    at spawnChild (ext:runtime/40_process.js:206:10)
    at Command.spawn (ext:runtime/40_process.js:474:12)
    at runCommand (https://deno.land/x/astral@0.3.5/src/browser.ts:13:27)
    at launch (https://deno.land/x/astral@0.3.5/src/browser.ts:254:39)
    at eventLoopTick (ext:core/01_core.js:166:7)
    at async <anonymous>:1:38
```

Environment Information:
Raspberry Pi 4b+ 4GB + 512 GB SSD
Ubuntu Server 23.10
Deno 1.41.1

**Comment by lino-levan** [comment]
Okay, it appears we're blocked on upstream here (https://github.com/GoogleChromeLabs/chrome-for-testing/issues/1). Astral could still work for you, but you're going to have to download a browser manually and set the `path` argument in launch. Let me know if I can assist you with this workaround.

**Comment by jimmont** [comment]
as-yet untested possible/likely solution
```sh
sudo apt install chromium-browser chromium-codecs-ffmpeg
which chromium
/usr/bin/chromium
```

```js 
...
const browser = await launch({
  // debian specific path option
  path: '/usr/bin/chromium',
  args: ['--remote-debugging-port=9222', '--headless=new', '--no-first-run', '--password-store=basic', '--use-mock-keychain', '--hide-scrollbars', '--no-sandbox']
 });
...
```

**Comment by KTibow** [comment]
can confirm jimmont's solution works (after switching `chromium` to `chromium-browser` for me)
